# Generated by Django 4.1.7 on 2023-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_rename_categorie_produit_catégorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
